development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://fotklmxmmsfkjc:71e355998cf460edb9d525444c63c85743c944ec4052b2fdd10d002ff0bfed02@ec2-54-163-230-219.compute-1.amazonaws.com:5432/d8cbp6i0bs0p4g
  channel_prefix: nameofapp_production
